"""Name and place mappings for the task 6 cleaning scripts.

Standard naming: OpenHalalan's province names.
"""

# HF memberships province names -> standard names
HF_PROVINCE_MAP = {
    "NCR, CITY OF MANILA, FIRST DISTRICT": "NCR FIRST DISTRICT",
    "NCR, SECOND DISTRICT": "NCR SECOND DISTRICT",
    "NCR, THIRD DISTRICT": "NCR THIRD DISTRICT",
    "NCR, FOURTH DISTRICT": "NCR FOURTH DISTRICT",
    "TAWI-TAWI": "TAWI TAWI",
    "COMPOSTELA VALLEY": "DAVAO DE ORO",
}

# Town names (after norm_town) -> standard names. Used for every source.
TOWN_MAP = {
    # HF typos and abbreviations
    "MAGADALENA": "MAGDALENA",
    "SAM NARCISO": "SAN NARCISO",
    "PRES CARLOS P GARCIA": "PRESIDENT CARLOS P GARCIA",
    "CORDOBA": "CORDOVA",
    # OpenHalalan variants of the same town
    "PRES C P GARCIA": "PRESIDENT CARLOS P GARCIA",
    "PRES CARLOS P GARCIA PITOGO": "PRESIDENT CARLOS P GARCIA",
    # Taguig-Pateros congressional district (House rows only)
    "PATEROS TAGUIG": "TAGUIG PATEROS",
    # OpenHalalan old-name variants (suggested by code, reviewed)
    "ALFONSO LISTA POTIA": "ALFONSO LISTA",
    "AMLAN AYUQUITAN": "AMLAN",
    "ASUNCION SAUG": "ASUNCION",
    "BALAGTAS BIGAA": "BALAGTAS",
    "BALINDONG WATU": "BALINDONG",
    "BASILISA RIZAL": "BASILISA",
    "CALANASAN BAYAG": "CALANASAN",
    "DARAGA LOCSIN": "DARAGA",
    "DATU ODIN SINSUAT DINAIG": "DATU ODIN SINSUAT",
    "DELFIN ALBANO MAGSAYSAY": "DELFIN ALBANO",
    "DON VICTORIANO CHIONGBIAN DON MARIANO MARCOS": "DON VICTORIANO CHIONGBIAN",
    "ENRIQUE B MAGALONA SARAVIA": "ENRIQUE B MAGALONA",
    "EL NIDO BACUIT": "EL NIDO",
    "GENERAL TINIO PAPAYA": "GENERAL TINIO",
    "GREGORIO DEL PILAR CONCEPCION": "GREGORIO DEL PILAR",
    "HINOBA AN ASIA": "HINOBA AN",
    "JOSE ABAD SANTOS TRINIDAD": "JOSE ABAD SANTOS",
    "JOSE DALMAN PONOT": "JOSE DALMAN",
    "KABUNTALAN TUMBAO": "KABUNTALAN",
    "LAAK SAN VICENTE": "LAAK",
    "LAMBAYONG MARIANO MARCOS": "LAMBAYONG",
    "LAPU LAPU CITY OPON": "LAPU LAPU",
    "LIBJO ALBOR": "LIBJO",
    "LICUAN BAAY LICUAN": "LICUAN BAAY",
    "LUMBA BAYABAO MAGUING": "LUMBA BAYABAO",
    "MABINI DONA ALICIA": "MABINI",
    "MAGSAYSAY LINUGOS": "MAGSAYSAY",
    "MAPUN CAGAYAN DE TAWI TAWI": "MAPUN",
    "MARAGUSAN SAN MARIANO": "MARAGUSAN",
    "MENDEZ MENDEZ NUNEZ": "MENDEZ",
    "MOISES PADILLA MAGALLON": "MOISES PADILLA",
    "PANGANIBAN PAYO": "PANGANIBAN",
    "PANGLIMA SUGALA BALIMBING": "PANGLIMA SUGALA",
    "PARANAS WRIGHT": "PARANAS",
    "PICONG SULTAN GUMANDER": "PICONG",
    "PINAN NEW PINAN": "PINAN",
    "PIO V CORPUZ LIMBUHAN": "PIO V CORPUZ",
    "POONA BAYABAO GATA": "POONA BAYABAO",
    "PRESENTACION PARUBCAN": "PRESENTACION",
    "QUIRINO ANGKAKI": "QUIRINO",
    "RAMON MAGSAYSAY LIARGO": "RAMON MAGSAYSAY",
    "RIZAL LIWAN": "RIZAL",
    "RIZAL MARCOS": "RIZAL",
    "RODRIGUEZ MONTALBAN": "RODRIGUEZ",
    "SAGBAYAN BORJA": "SAGBAYAN",
    "SAN ANDRES CALOLBON": "SAN ANDRES",
    "SAN FRANCISCO ANAO AON": "SAN FRANCISCO",
    "SAN FRANCISCO AURORA": "SAN FRANCISCO",
    "SAN LORENZO RUIZ IMELDA": "SAN LORENZO RUIZ",
    "SANTA MARIA IMELDA": "SANTA MARIA",
    "SANTA MONICA SAPAO": "SANTA MONICA",
    "SANTO DOMINGO LIBOG": "SANTO DOMINGO",
    "SANTO NINO FAIRE": "SANTO NINO",
    "SHARIFF AGUAK MAGANOY": "SHARIFF AGUAK",
    "SOMINOT DON MARIANO MARCOS": "SOMINOT",
    "SULTAN KUDARAT NULING": "SULTAN KUDARAT",
    "SULTAN SA BARONGIS LAMBAYONG": "SULTAN SA BARONGIS",
    "TOBIAS FORNIER DAO": "TOBIAS FORNIER",
    "VALENCIA LUZURRIAGA": "VALENCIA",
    # OpenHalalan names that HF never uses, and Caloocan's three spellings (reviewed in notebook 07)
    "AMAI MANABILANG": "BUMBARAN",
    "AMAI MANABILANG BUMBARAN": "BUMBARAN",
    "BACOLOD KALAWI BACOLOD GRANDE": "BACOLOD KALAWI",
    "BACUNGAN LEON T POSTIGO": "BACUNGAN",
    "BALIWAG": "BALIUAG",
    "BANAY BANAY": "BANAYBANAY",
    "BAYAWAN CITY TULONG": "BAYAWAN",
    "BINDOY PAYABON": "BINDOY",
    "BROOKE S POINT": "BROOKES POINT",
    "BULALACAO SAN PEDRO": "BULALACAO",
    "D V CHIONGBIAN D M MARCOS": "DON VICTORIANO CHIONGBIAN",
    "DON V CHIONGBIAN": "DON VICTORIANO CHIONGBIAN",
    "DUMAGUETE CITY CAPITAL": "DUMAGUETE",
    "GABALDON BITULOK & SABANI": "GABALDON",
    "GABALDON BITULOK AND SABANI": "GABALDON",
    "GENERAL SANTOS CITY DADIANGAS": "GENERAL SANTOS",
    "GETAFE": "JETAFE",
    "HADJI PANGLIMA TAHIL MARUNGGAS": "HADJI PANGLIMA TAHIL",
    "JAVIER BUGHO": "JAVIER",
    "JOLO CAPITAL": "JOLO",
    "KABUGAO CAPITAL": "KABUGAO",
    "KALOOCAN": "CALOOCAN",
    "KALOOKAN": "CALOOCAN",
    "LA TRINIDAD CAPITAL": "LA TRINIDAD",
    "LAGAWE BURNAY": "LAGAWE",
    "LEON T POSTIGO": "BACUNGAN",
    "M LANG": "MLANG",
    "MASUI": "MASIU",
    "MATAASNAKAHOY": "MATAAS NA KAHOY",
    "PAGAYAWAN TATARIKAN": "PAGAYAWAN",
    "PANGLIMA ESTINO NEW PANAMAO": "PANGLIMA ESTINO",
    "PARACELIS PARACALES": "PARACELIS",
    "PINAMUNGAJAN": "PINAMUNGAHAN",
    "PIO V CORPUS": "PIO V CORPUZ",
    "POZORRUBIO": "POZZORUBIO",
    "S N DIMAPORO KAROMATAN": "SULTAN NAGA DIMAPORO",
    "SAL LAPADAN": "SALLAPADAN",
    "SALCEDO BAUGEN": "SALCEDO",
    "SAN JUAN CABALIAN": "SAN JUAN",
    "SAN JUAN LAPOG": "SAN JUAN",
    "SAN POLICARPIO": "SAN POLICARPO",
    "SASMUAN SEXMOAN": "SASMUAN",
    "SHARIFF AGUAK CAPITAL": "SHARIFF AGUAK",
    "STO TOMAS": "SANTO TOMAS",
    "SULTAN GUMANDER": "PICONG",
    "SULTAN NAGA DIMAPORO KAROMATAN": "SULTAN NAGA DIMAPORO",
    "T BOLI": "TBOLI",
    "TACLOBAN CITY CAPITAL": "TACLOBAN",
    # Found by the town label check (HF 2016 and OpenHalalan also write it this way)
    "BANNA ESPIRITU": "BANNA",
}
  

# Province-specific town fixes: (province group, town after TOWN_MAP) -> standard name
PROVINCE_TOWN_MAP = {
    ("LANAO DEL SUR", "TAGOLOAN"): "TAGOLOAN II",
    # Ateneo 1988-1998 names that no other source uses (reviewed in notebook 07)
    ("ABRA", "BAAY LICUAN"): "LICUAN BAAY",
    ("ABRA", "LICUAN BAY"): "LICUAN BAAY",
    ("BATANGAS", "SAN PACUAL"): "SAN PASCUAL",
    ("BOHOL", "ANTEQUERRA"): "ANTEQUERA",
    ("BOHOL", "CATIGBI AN"): "CATIGBIAN",
    ("BOHOL", "PRES CP GARCIA"): "PRESIDENT CARLOS P GARCIA",
    ("BOHOL", "PRES GARCIA"): "PRESIDENT CARLOS P GARCIA",
    ("BOHOL", "PRESIDENTE CARLOS P GARCIA"): "PRESIDENT CARLOS P GARCIA",
    ("BUKIDNON", "IMPASUGONG"): "IMPASUG ONG",
    ("BUKIDNON", "MALAYBALAYY"): "MALAYBALAY",
    ("BULACAN", "BUSANTO S"): "BUSTOS",
    ("CAGAYAN", "LALLO"): "LAL LO",
    ("CAMARINES SUR", "GARCHITORINA"): "GARCHITORENA",
    ("CAPIZ", "MAAYON"): "MA AYON",
    ("CAPIZ", "SAPIAN"): "SAPI AN",
    ("CAVITE", "GEN E AGUINALDO"): "GENERAL EMILIO AGUINALDO",
    ("CAVITE", "GEN M ALVAREZ"): "GEN MARIANO ALVAREZ",
    ("CAVITE", "GEN TRIAS"): "GENERAL TRIAS",
    ("CAVITE", "GENERAL MARIANO ALVAREZ"): "GEN MARIANO ALVAREZ",
    ("CAVITE", "MENDEZ NUNEZ"): "MENDEZ",
    ("CAVITE", "NOVOLETA"): "NOVELETA",
    ("CEBU", "BOUOON"): "BOLJOON",
    ("CEBU", "MADRILEJOS"): "MADRIDEJOS",
    ("CEBU", "SAN REMEGIO"): "SAN REMIGIO",
    ("COTABATO", "MILANG"): "MLANG",
    ("COTABATO", "PIGCAWAYAN"): "PIGKAWAYAN",
    ("DAVAO DEL NORTE", "KAPUT IAN"): "KAPUTIAN",
    ("DAVAO DEL NORTE", "MONTEVISANTA"): "MONTEVISTA",
    ("DAVAO DEL NORTE", "SAN MARIANO"): "MARAGUSAN",
    ("DAVAO DEL NORTE", "SAN VICENTE"): "LAAK",
    ("DAVAO DEL SUR", "MAUTA"): "MALITA",
    ("DAVAO DEL SUR", "PALADA"): "PADADA",
    ("EASTERN SAMAR", "GEN MACARTHUR"): "GENERAL MACARTHUR",
    ("EASTERN SAMAR", "GENERAL MACARHUR"): "GENERAL MACARTHUR",
    ("EASTERN SAMAR", "GENERAL MCARTHUR"): "GENERAL MACARTHUR",
    ("EASTERN SAMAR", "LAWA AN"): "LAWAAN",
    ("IFUGAO", "AGUINALDC"): "AGUINALDO",
    ("IFUGAO", "POTIA"): "ALFONSO LISTA",
    ("ILOCOS NORTE", "ESPIRITU"): "BANNA",
    ("ILOCOS NORTE", "NUEVA ECIJA"): "NUEVA ERA",
    ("ILOCOS SUR", "NARVARCAN"): "NARVACAN",
    ("ISABELA", "CAUAYAM"): "CAUAYAN",
    ("ISABELA", "DIVILICAN"): "DIVILACAN",
    ("LAGUNA", "KALAYAN"): "KALAYAAN",
    ("LAGUNA", "SINLOAN"): "SINILOAN",
    ("LANAO DEL NORTE", "BALO I"): "BALOI",
    ("LANAO DEL NORTE", "KAROMATAN"): "SULTAN NAGA DIMAPORO",
    ("LANAO DEL SUR", "BACOLOD GRANDE"): "BACOLOD KALAWI",
    ("LANAO DEL SUR", "BUADIPUSO BUNTONG"): "BUADIPOSO BUNTONG",
    ("LANAO DEL SUR", "LUMBAYANGUE"): "LUMBAYANAGUE",
    ("LANAO DEL SUR", "MAO"): "WAO",
    ("LANAO DEL SUR", "MOLUNDO"): "MULONDO",
    ("LEYTE", "V ALANGALANG"): "ALANGALANG",
    ("MAGUINDANAO", "BOLUAN"): "BULUAN",
    ("MAGUINDANAO", "DINAIG"): "DATU ODIN SINSUAT",
    ("MAGUINDANAO", "GEN SK PENDATUN"): "GEN S K PENDATUN",
    ("MAGUINDANAO", "MAGANOY"): "SHARIFF AGUAK",
    ("MAGUINDANAO", "MAGANOY CAPITAL"): "SHARIFF AGUAK",
    ("MASBATE", "PIO VCORPUZ"): "PIO V CORPUZ",
    ("MISAMIS OCCIDENTAL", "DON MARIANO MARCOS"): "DON VICTORIANO CHIONGBIAN",
    ("MISAMIS OCCIDENTAL", "OZAMIZ"): "OZAMIS",
    ("MISAMIS ORIENTAL", "BINUANIGAN"): "BINUANGAN",
    ("MISAMIS ORIENTAL", "KINOGITAN"): "KINOGUITAN",
    ("NCR FOURTH DISTRICT", "TAGIG"): "TAGUIG",
    ("NCR THIRD DISTRICT", "MALABON NAVOTAS"): "NAVOTAS",
    ("NEGROS OCCIDENTAL", "E B MAGALONA"): "ENRIQUE B MAGALONA",
    ("NEGROS OCCIDENTAL", "ENRIQUE BMAGALONA"): "ENRIQUE B MAGALONA",
    ("NEGROS OCCIDENTAL", "SAN SILAY"): "SILAY",
    ("NUEVA ECIJA", "GEN NATIVIDAD"): "GENERAL MAMERTO NATIVIDAD",
    ("NUEVA ECIJA", "GEN TINIO"): "GENERAL TINIO",
    ("NUEVA ECIJA", "MUNOZ"): "SCIENCE CITY OF MUNOZ",
    ("NUEVA ECIJA", "PANARANDA"): "PENARANDA",
    ("NUEVA ECIJA", "TALUGTOG"): "TALUGTUG",
    ("NUEVA ECIJA", "ZARAGOSA"): "ZARAGOZA",
    ("NUEVA VIZCAYA", "ALFREDO CASTANEDA"): "ALFONSO CASTANEDA",
    ("NUEVA VIZCAYA", "VILLA VERDE"): "VILLAVERDE",
    ("OCCIDENTAL MINDORO", "ABRA DEL ILOG"): "ABRA DE ILOG",
    ("ORIENTAL MINDORO", "BULALAKAO"): "BULALACAO",
    ("PALAWAN", "BATARASA"): "BATARAZA",
    ("PALAWAN", "MARCOS"): "RIZAL",
    ("PAMPANGA", "SEXMOAN"): "SASMUAN",
    ("PANGASINAN", "AG NO"): "AGNO",
    ("QUEZON", "JUMALIG"): "JOMALIG",
    ("RIZAL", "JALAJALA"): "JALA JALA",
    ("ROMBLON", "SAN LORENZO RUIZ"): "SANTA MARIA",
    ("SAMAR", "TARAGNAN"): "TARANGNAN",
    ("SAMAR", "WRIGHT"): "PARANAS",
    ("SOUTH COTABATO", "GEN SANTOS"): "GENERAL SANTOS",
    ("SULTAN KUDARAT", "LEBAE"): "LEBAK",
    ("SULTAN KUDARAT", "PRES QUIRINO"): "PRESIDENT QUIRINO",
    ("SULU", "KALINGGALAN CALUANG"): "KALINGALAN CALUANG",
    ("SULU", "MARUNGAS"): "HADJI PANGLIMA TAHIL",
    ("SULU", "MARUNGGAS"): "HADJI PANGLIMA TAHIL",
    ("SULU", "NEW PANAMAO"): "PANGLIMA ESTINO",
    ("SULU", "PANAMAO"): "OLD PANAMAO",
    ("SURIGAO DEL NORTE", "GEN LUNA"): "GENERAL LUNA",
    ("SURIGAO DEL NORTE", "GIGAGUIT"): "GIGAQUIT",
    ("SURIGAO DEL NORTE", "LIBIO"): "LIBJO",
    ("SURIGAO DEL SUR", "BOROBO"): "BAROBO",
    ("SURIGAO DEL SUR", "CASWAIT"): "CAGWAIT",
    ("TAWI TAWI", "BALIMBING"): "PANGLIMA SUGALA",
    ("TAWI TAWI", "CAGAYAN DE TAW"): "MAPUN",
    ("ZAMBOANGA DEL NORTE", "JOSE DALMAN (PONOD"): "JOSE DALMAN",
    ("ZAMBOANGA DEL NORTE", "LEON B POSTIGO"): "BACUNGAN",
    ("ZAMBOANGA DEL NORTE", "PRESIDENT ROXAS"): "PRES MANUEL A ROXAS",
    ("ZAMBOANGA DEL NORTE", "SERGIO OSMENHA SR"): "SERGIO OSMENA SR",
    ("ZAMBOANGA DEL SUR", "DON MARIANO MARCOS"): "SOMINOT",
    ("ZAMBOANGA DEL SUR", "VINCENZO SAGUN"): "VINCENZO A SAGUN",
}


# PSA poverty district keys -> standard province names
PSA_AREA_MAP = {
    "1ST DISTRICT": "NCR FIRST DISTRICT",
    "2ND DISTRICT": "NCR SECOND DISTRICT",
    "3RD DISTRICT": "NCR THIRD DISTRICT",
    "4TH DISTRICT": "NCR FOURTH DISTRICT",
}

# Cities that PSA reports like provinces: area_key -> (province, town)
PSA_CITY_MAP = {
    "COTABATO CITY": ("MAGUINDANAO", "COTABATO"),
    "ISABELA CITY": ("BASILAN", "ISABELA"),
}


# Roster period names: typo fixes (applied as text replacements)
PERIOD_TYPO_MAP = {
    "Philipine": "Philippine",
    "Pamabansa": "Pambansa",
    "Pambasa": "Pambansa",
    "Congresss": "Congress",
    "Asssembly": "Assembly",
    "thCongress": "th Congress",
    "Legislative": "Legislature",
    "Batasan Pambansa": "Batasang Pambansa",
    "Commenwealth": "Commonwealth",
}

# Ordinal words at the start of a period name -> numbers
ORDINAL_WORDS = {
    "FIRST": 1, "SECOND": 2, "THIRD": 3, "FOURTH": 4, "FIFTH": 5, "SIXTH": 6,
    "SEVENTH": 7, "EIGHTH": 8, "NINTH": 9, "TENTH": 10, "ELEVENTH": 11, "TWELFTH": 12,
    "THIRTEENTH": 13, "FOURTEENTH": 14, "FIFTEENTH": 15, "SIXTEENTH": 16,
    "SEVENTEENTH": 17, "EIGHTEENTH": 18, "NINETEENTH": 19, "TWENTIETH": 20,
}

# Remaining period variants -> one standard name
PERIOD_MAP = {
    "1st National Assembly Commonwealth": "1st Commonwealth National Assembly",
    "1st Congress Commonwealth": "1st Congress of Commonwealth",
}


# Roster region_province (uppercased, no asterisks) -> standard province, or a city for the lookup
ROSTER_PROVINCE_MAP = {
    # Typos
    "COMPOSTELLA VALLEY": "DAVAO DE ORO",
    "SOUTH COTOBATO": "SOUTH COTABATO",
    "NUEVA VISCAYA": "NUEVA VIZCAYA",
    "ZAMBOAGA SIBUGAY": "ZAMBOANGA SIBUGAY",
    # Old or alternate names
    "COMPOSTELA VALLEY": "DAVAO DE ORO",
    "WESTERN SAMAR": "SAMAR",
    "DINAGAT ISLAND": "DINAGAT ISLANDS",
    "TAWI-TAWI": "TAWI TAWI",
    # Shared districts -> one of their places, resolved by the city lookup
    "TAGUIG-PATEROS": "TAGUIG CITY",
    "TAGUIG CITY-PATEROS": "TAGUIG CITY",
    "TAGUIG CITY/PATEROS": "TAGUIG CITY",
    "MALABON / NAVOTAS": "MALABON CITY",
    "MALABON-NAVOTAS": "MALABON CITY",
    "MALABON-NAVOTAS CITY": "MALABON CITY",
    "SOUTH COTABATO AND GENERAL SANTOS CITY": "SOUTH COTABATO",
    "MAGUINDANAO AND COTABATO CITY": "MAGUINDANAO",
    "MAGUINDANAO WITH COTABATO CITY": "MAGUINDANAO",
    "SHARIFF KABUNSUAN WITH COTABATO CITY": "MAGUINDANAO",
    # Found in testing
    "NORTH COTABATO": "COTABATO",
    "NORTH COTOBATO": "COTABATO",
    "PATEROS/TAGUIG": "TAGUIG CITY",
    "LAS PIÑAS-MUNTINLUPA CITY": "LAS PIÑAS CITY",
    "LAS PIÑAS/MUNTINLUPA": "LAS PIÑAS CITY",
    "SAN JUAN-MANDALUYONG": "MANDALUYONG CITY",
}


# Roster city names that exist in several provinces: name -> (province, town)
ROSTER_CITY_MAP = {
    "QUEZON CITY": ("NCR SECOND DISTRICT", "QUEZON"),
    "BACOLOD CITY": ("NEGROS OCCIDENTAL", "BACOLOD"),
    "SAN JUAN CITY": ("NCR SECOND DISTRICT", "SAN JUAN"),
    "SAN JUAN": ("NCR SECOND DISTRICT", "SAN JUAN"),
}

# Roster rows with a blank province, recovered from OpenHalalan House records: name -> province
ROSTER_MISSING_PROVINCE = {
    "DIMAPORO, IMELDA Q.": "LANAO DEL NORTE",
    "FLORES, FLORENCIO JR. T.": "BUKIDNON",
}
# Ateneo province names -> standard names
ATENEO_PROVINCE_MAP = {
    "NCR - MANILA": "NCR FIRST DISTRICT",
    "NCR - SECOND DISTRICT": "NCR SECOND DISTRICT",
    "NCR - THIRD DISTRICT": "NCR THIRD DISTRICT",
    "NCR - FOURTH DISTRICT": "NCR FOURTH DISTRICT",
    "TAWI-TAWI": "TAWI TAWI",
}

# Provinces created from another province -> the province they came from (year created),
# so people and towns can be linked across the split
PROVINCE_GROUP = {
    "ZAMBOANGA SIBUGAY": "ZAMBOANGA DEL SUR",      # 2001
    "DAVAO DE ORO": "DAVAO DEL NORTE",             # 1998
    "DAVAO OCCIDENTAL": "DAVAO DEL SUR",           # 2013
    "SARANGANI": "SOUTH COTABATO",                 # 1992
    "BILIRAN": "LEYTE",                            # 1992
    "GUIMARAS": "ILOILO",                          # 1992
    "DINAGAT ISLANDS": "SURIGAO DEL NORTE",        # 2006
    "MAGUINDANAO DEL NORTE": "MAGUINDANAO",        # 2022
    "MAGUINDANAO DEL SUR": "MAGUINDANAO",          # 2022
    "SPECIAL GEOGRAPHIC AREA": "COTABATO",         # 2019, villages from Cotabato
    "APAYAO": "KALINGA",                           # 1995, Kalinga-Apayao split
}

# Each Metro Manila city belongs to exactly one NCR district (town names after norm_town)
NCR_DISTRICT_OF_TOWN = {
    "MANILA": "NCR FIRST DISTRICT",
    "MANDALUYONG": "NCR SECOND DISTRICT",
    "MARIKINA": "NCR SECOND DISTRICT",
    "PASIG": "NCR SECOND DISTRICT",
    "QUEZON": "NCR SECOND DISTRICT",
    "SAN JUAN": "NCR SECOND DISTRICT",
    "CALOOCAN": "NCR THIRD DISTRICT",
    "MALABON": "NCR THIRD DISTRICT",
    "NAVOTAS": "NCR THIRD DISTRICT",
    "VALENZUELA": "NCR THIRD DISTRICT",
    "LAS PINAS": "NCR FOURTH DISTRICT",
    "MAKATI": "NCR FOURTH DISTRICT",
    "MUNTINLUPA": "NCR FOURTH DISTRICT",
    "PARANAQUE": "NCR FOURTH DISTRICT",
    "PASAY": "NCR FOURTH DISTRICT",
    "PATEROS": "NCR FOURTH DISTRICT",
    "TAGUIG": "NCR FOURTH DISTRICT",
}

# Towns that existed only before 2001, so HF and OpenHalalan never list them: (province group, town)
HISTORICAL_TOWNS = {
    ("DAVAO DEL NORTE", "BABAK"),     # merged into Island Garden City of Samal in 1998
    ("DAVAO DEL NORTE", "KAPUTIAN"),  # merged into Island Garden City of Samal in 1998
    ("DAVAO DEL NORTE", "SAMAL"),     # merged into Island Garden City of Samal in 1998
    ("SORSOGON", "BACON"),            # merged with Sorsogon town into Sorsogon City in 2000
}

# Ateneo rows filed under the wrong place in one election: (year, province, town) -> (right province, right town)
ATENEO_PLACE_FIXES = {
    (1988, "NORTHERN SAMAR", "SAN ROQUE"): ("NORTHERN SAMAR", "SAN VICENTE"),     # the two labels are swapped
    (1988, "NORTHERN SAMAR", "SAN VICENTE"): ("NORTHERN SAMAR", "SAN ROQUE"),
    (1988, "PALAWAN", "ROXAS"): ("PALAWAN", "SAN VICENTE"),                       # the two labels are swapped
    (1988, "PALAWAN", "SAN VICENTE"): ("PALAWAN", "ROXAS"),
    (1988, "NUEVA ECIJA", "LAUR"): ("NUEVA ECIJA", "LUPAO"),                      # LUPAO's officials
    (1995, "DAVAO DEL NORTE", "BRAULIO E DUJALI"): ("DAVAO DEL NORTE", "BABAK"),  # BABAK's officials; the town was created in 1998
    (1995, "MAGUINDANAO", "MARAWI"): ("LANAO DEL SUR", "MARAWI"),                # written "MARAWI CITY (LANAO DEL SUR)"
}