"""Name and place mappings for the task 6 cleaning scripts.

Standard naming: OpenHalalan's province names.
"""

# HF memberships province names -> standard names
HF_PROVINCE_MAP = {
    "NCR, CITY OF MANILA, FIRST DISTRICT": "NCR FIRST DISTRICT",
    "NCR, SECOND DISTRICT": "NCR SECOND DISTRICT",
    "NCR, THIRD DISTRICT": "NCR THIRD DISTRICT",
    "NCR, FOURTH DISTRICT": "NCR FOURTH DISTRICT",
    "TAWI-TAWI": "TAWI TAWI",
    "COMPOSTELA VALLEY": "DAVAO DE ORO",
}

# Town names (after norm_town) -> standard names. Used for every source.
TOWN_MAP = {
    # HF typos and abbreviations
    "MAGADALENA": "MAGDALENA",
    "SAM NARCISO": "SAN NARCISO",
    "PRES CARLOS P GARCIA": "PRESIDENT CARLOS P GARCIA",
    # OpenHalalan variants of the same town
    "PRES C P GARCIA": "PRESIDENT CARLOS P GARCIA",
    "PRES CARLOS P GARCIA PITOGO": "PRESIDENT CARLOS P GARCIA",
    # Taguig-Pateros congressional district (House rows only)
    "PATEROS TAGUIG": "TAGUIG PATEROS",
    # OpenHalalan old-name variants (suggested by code, reviewed)
    "ALFONSO LISTA POTIA": "ALFONSO LISTA",
    "AMLAN AYUQUITAN": "AMLAN",
    "ASUNCION SAUG": "ASUNCION",
    "BALAGTAS BIGAA": "BALAGTAS",
    "BALINDONG WATU": "BALINDONG",
    "BASILISA RIZAL": "BASILISA",
    "CALANASAN BAYAG": "CALANASAN",
    "DARAGA LOCSIN": "DARAGA",
    "DATU ODIN SINSUAT DINAIG": "DATU ODIN SINSUAT",
    "DELFIN ALBANO MAGSAYSAY": "DELFIN ALBANO",
    "DON VICTORIANO CHIONGBIAN DON MARIANO MARCOS": "DON VICTORIANO CHIONGBIAN",
    "EL NIDO BACUIT": "EL NIDO",
    "GENERAL TINIO PAPAYA": "GENERAL TINIO",
    "GREGORIO DEL PILAR CONCEPCION": "GREGORIO DEL PILAR",
    "HINOBA AN ASIA": "HINOBA AN",
    "JOSE ABAD SANTOS TRINIDAD": "JOSE ABAD SANTOS",
    "JOSE DALMAN PONOT": "JOSE DALMAN",
    "KABUNTALAN TUMBAO": "KABUNTALAN",
    "LAAK SAN VICENTE": "LAAK",
    "LAMBAYONG MARIANO MARCOS": "LAMBAYONG",
    "LAPU LAPU CITY OPON": "LAPU LAPU",
    "LIBJO ALBOR": "LIBJO",
    "LICUAN BAAY LICUAN": "LICUAN BAAY",
    "LUMBA BAYABAO MAGUING": "LUMBA BAYABAO",
    "MABINI DONA ALICIA": "MABINI",
    "MAGSAYSAY LINUGOS": "MAGSAYSAY",
    "MAPUN CAGAYAN DE TAWI TAWI": "MAPUN",
    "MARAGUSAN SAN MARIANO": "MARAGUSAN",
    "MENDEZ MENDEZ NUNEZ": "MENDEZ",
    "MOISES PADILLA MAGALLON": "MOISES PADILLA",
    "PANGANIBAN PAYO": "PANGANIBAN",
    "PANGLIMA SUGALA BALIMBING": "PANGLIMA SUGALA",
    "PARANAS WRIGHT": "PARANAS",
    "PICONG SULTAN GUMANDER": "PICONG",
    "PINAN NEW PINAN": "PINAN",
    "PIO V CORPUZ LIMBUHAN": "PIO V CORPUZ",
    "POONA BAYABAO GATA": "POONA BAYABAO",
    "PRESENTACION PARUBCAN": "PRESENTACION",
    "QUIRINO ANGKAKI": "QUIRINO",
    "RAMON MAGSAYSAY LIARGO": "RAMON MAGSAYSAY",
    "RIZAL LIWAN": "RIZAL",
    "RIZAL MARCOS": "RIZAL",
    "RODRIGUEZ MONTALBAN": "RODRIGUEZ",
    "SAGBAYAN BORJA": "SAGBAYAN",
    "SAN ANDRES CALOLBON": "SAN ANDRES",
    "SAN FRANCISCO ANAO AON": "SAN FRANCISCO",
    "SAN FRANCISCO AURORA": "SAN FRANCISCO",
    "SAN LORENZO RUIZ IMELDA": "SAN LORENZO RUIZ",
    "SANTA MARIA IMELDA": "SANTA MARIA",
    "SANTA MONICA SAPAO": "SANTA MONICA",
    "SANTO DOMINGO LIBOG": "SANTO DOMINGO",
    "SANTO NINO FAIRE": "SANTO NINO",
    "SHARIFF AGUAK MAGANOY": "SHARIFF AGUAK",
    "SOMINOT DON MARIANO MARCOS": "SOMINOT",
    "SULTAN KUDARAT NULING": "SULTAN KUDARAT",
    "SULTAN SA BARONGIS LAMBAYONG": "SULTAN SA BARONGIS",
    "TOBIAS FORNIER DAO": "TOBIAS FORNIER",
    "VALENCIA LUZURRIAGA": "VALENCIA",
}

# Province-specific town fixes, for names that are valid in other provinces
PROVINCE_TOWN_MAP = {
    ("LANAO DEL SUR", "TAGOLOAN"): "TAGOLOAN II",
}